### ISSUE TITLE
Recipe Name Collisions

### ISSUE THREAD

**Issue by Conorrr** [user24/auntiesrecipes#4]
I noticed that because you use the recipe name as the key you cannot have different recipes with the same name and therefore are missing some recipes:

E.G 
http://www.bbc.co.uk/food/recipes/yorkshirepudding_93848
http://www.bbc.co.uk/food/recipes/yorkshire_pudding_69240

These are both named: `Yorkshire Pudding` and therefore only can only store 1 of them in your current format. The easiest way to fix this would be to change the json format to something like:

```
{
  "Recipe name":[{recipe1},{recipe2}],
  "Recipe name":[{recipe3},{recipe4}],
  ...
}
```

That way you don't have to change the search logic and it's a trivial change to return the additional recipes.

I have compiled a list of the missing recipes: https://gist.github.com/Conorrr/5fbe72535872d6b35d3219c38586f415

**Comment by user24** [comment]
Hi,

Thanks for spotting this. I'll regenerate the titles json and see what I can do. I'm loath to add more bulk to that file as it's already over a meg, but sticking the recipe objects in an array where necessary shouldn't add too much weight.

Normally I'd say we should make every key contain an array even if length is 1, but in the interest of keeping the file size down I would prefer keys to contain either one recipe object or an array. Slightly messier API, but should save a few kb.

While I'm at it I might stick a flag in there to indicate whether the recipe has an image or not, that would stop 404s.

**Comment by user24** [comment]
Fixed, now I'm indexing on url and having title as a property: https://github.com/user24/auntiesrecipes/commit/f3e516f54dd200c88edf11a34ba321276bd171da
